In [2]:
import pandas as pd

url = "https://github.com/Richoivan/Bussines-Intelegence/raw/main/E-Commerce-Train%20(1).csv"

df = pd.read_csv(url)

df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10999 non-null  int64
 1   Warehouse_block      10999 non-null  object
 2   Mode_of_Shipment     10999 non-null  object
 3   Customer_care_calls  10999 non-null  int64
 4   Customer_rating      10999 non-null  int64
 5   Cost_of_the_Product  10999 non-null  int64
 6   Prior_purchases      10999 non-null  int64
 7   Product_importance   10999 non-null  object
 8   Gender               10999 non-null  object
 9   Discount_offered     10999 non-null  int64
 10  Weight_in_gms        10999 non-null  int64
 11  Reached.on.Time_Y.N  10999 non-null  int64
dtypes: int64(8), object(4)
memory usage: 1.0+ MB

In [4]:
df.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [6]:
#create column delay_Flag
df['Delay_Flag'] = df['Reached.on.Time_Y.N'].apply(lambda x: 'Late' if x == 1 else 'On Time')

In [7]:
#create column weight Category
def weight_category(w):
    if w < 1500:
        return 'Light'
    elif w <= 3000:
        return 'Medium'
    else:
        return 'Heavy'

df['Weight_Category'] = df['Weight_in_gms'].apply(weight_category)

In [8]:
#create column Discount Bucket
def discount_bucket(d):
    if d <= 20:
        return 'Low'
    elif d <= 50:
        return 'Medium'
    else:
        return 'High'

df['Discount_Bucket'] = df['Discount_offered'].apply(discount_bucket)

In [9]:
#create column Rating Category
def rating_category(r):
    if r <= 2:
        return 'Low'
    elif r == 3:
        return 'Medium'
    else:
        return 'High'

df['Rating_Category'] = df['Customer_rating'].apply(rating_category)

In [10]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Delay_Flag,Weight_Category,Discount_Bucket,Rating_Category
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,Late,Light,Medium,Low
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,Late,Heavy,High,High
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,Late,Heavy,Medium,Low
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1,Late,Light,Low,Medium
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1,Late,Medium,Medium,Low

In [11]:
df.to_csv("ECommerce_Train_Prepared.csv", index=False)
from google.colab import files
files.download("ECommerce_Train_Prepared.csv")